name: Code Quality
on: 
  push:
    branches:
      - "master"
jobs:
  code-quality:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Code analysis
        run: |
          go vet ./..
          golint -min_confidence 0.0 -set_exit_status ./..
