name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'
      - name: Run build
        run: go build .
      - name: Code analysis
        run: |
          go vet .
          golint .
      - name: Run testing
        run: go test -v ./...
